sudo: false
language: cpp
compiler:
  - gcc
addons:
  sonarcloud:
    organization: "walterjgsp-github" # the key of the org you chose at step #3
    token: $SONAR_TOKEN
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - make
  - make test