baseURL = "http://walterjgsp.github.io/algorithms/"
languageCode = "en-us"
title= "Algorithms"
pygmentsUseClasses=true
description = "Repository of algorithms, problems and structures that i have learned to help me and the others if needed."
Paginate = 5
[Params]
  RSSLink = "/index.xml"
  author = "walterjgsp" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "walterjgsp@gmail.com"

[[menu.main]]
    name = "Problems"
    weight = -100
    url = "/problems/"
[[menu.main]]
    name = "FAQ"
    weight = -90
    url = "/faq/"
